#!/bin/bash

[ -z $1 ] && {
    echo "ERROR: Missing name of directory with tests. Run like: ./test <folder-name-with-tests>"
    exit 1
}

files=($(ls $1 | sort -n))
for file in ${files[*]}
do
    file="$1/$file"
    echo "RUNNING: $file"
    cargo run 1 $(basename $file .cnf) < $file
done
